/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Avatar: typeof import('primevue/avatar')['default']
    BasePicker: typeof import('./src/components/utils/BasePicker.vue')['default']
    Button: typeof import('primevue/button')['default']
    BUtton: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    ClusterContainer: typeof import('./src/components/ClusterContainer.vue')['default']
    DatePicker: typeof import('primevue/datepicker')['default']
    Drawer: typeof import('primevue/drawer')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Listbox: typeof import('primevue/listbox')['default']
    MyDatepicker: typeof import('./src/components/utils/MyDatepicker.vue')['default']
    Panel: typeof import('primevue/panel')['default']
    Portal: typeof import('primevue/portal')['default']
    Primevuedatepicker: typeof import('./src/components/test/primevuedatepicker.vue')['default']
    ScrollPanel: typeof import('primevue/scrollpanel')['default']
    TasksList: typeof import('./src/components/TasksList.vue')['default']
    Test: typeof import('./src/components/utils/Test.vue')['default']
    Textarea: typeof import('primevue/textarea')['default']
  }
  export interface ComponentCustomProperties {
    Ripple: typeof import('primevue/ripple')['default']
  }
}
