/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Avatar: typeof import('primevue/avatar')['default']
    BasePicker: typeof import('./src/components/utils/BasePicker.vue')['default']
    Button: typeof import('primevue/button')['default']
    BUTton: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    ClusterContainer: typeof import('./src/components/ClusterContainer.vue')['default']
    ContentDiff: typeof import('./src/components/tasks/ContentDiff.vue')['default']
    DatePicker: typeof import('primevue/datepicker')['default']
    Dialog: typeof import('primevue/dialog')['default']
    Drawer: typeof import('primevue/drawer')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    InputNumber: typeof import('primevue/inputnumber')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Listbox: typeof import('primevue/listbox')['default']
    Message: typeof import('primevue/message')['default']
    MyDatepicker: typeof import('./src/components/utils/MyDatepicker.vue')['default']
    NewTaskAddOption: typeof import('./src/components/tasks/NewTaskAddOption.vue')['default']
    Panel: typeof import('primevue/panel')['default']
    Popover: typeof import('primevue/popover')['default']
    Portal: typeof import('primevue/portal')['default']
    Primevuedatepicker: typeof import('./src/components/test/primevuedatepicker.vue')['default']
    ProgressSpinner: typeof import('primevue/progressspinner')['default']
    ScrollPanel: typeof import('primevue/scrollpanel')['default']
    Select: typeof import('primevue/select')['default']
    SettingView: typeof import('./src/components/SettingView.vue')['default']
    TasksList: typeof import('./src/components/tasks/TasksList.vue')['default']
    Test: typeof import('./src/components/test/Test.vue')['default']
    Textarea: typeof import('primevue/textarea')['default']
  }
  export interface ComponentCustomProperties {
    Ripple: typeof import('primevue/ripple')['default']
  }
}
